---
abstract: "Contains regexps common across TSQL::AST and TSQL::SplitStatement\r"
author:
  - 'Ded MedVed <dedmedved@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TSQL-Common-Regexp
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Clone: 0
  IPC::System::Simple: 0
  Test::More: 0
  autodie: 0
  indirect: 0
  perl: 0
  version: 0
version: 0.04
